name: smart_personal_final_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8+4    # Add this for SQLite support
  sqflite_common_ffi: ^2.3.0+4   # ✅ Add this line
  path: ^1.8.3         # Add this to handle database file paths
  path_provider: ^2.1.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
